
pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/cworoud-bit/Ubuntu.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('devsecops-portfolio') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('devsecops-portfolio') {
                    sh 'npm run build'
                }
            }
        }
    }
}
